[DPE-3861] Switch to reusable workflows and add arm64 builds (#46)
* Bump deps

* Initial switch of workflows

* Tweak charmcraft.yaml

* Add groups

* Remove cache wrapper

* Build test charm

* Add a cloud_name fixture

* Add skip markers

* Set sysctl for opensearch

* Add arm64 base

* Update libjuju

* Increate PG tests idle timeout

* Apply suggestions from code review

Co-authored-by: Carl Csaposs <carl.csaposs@canonical.com>

* Code review fixes

* Cloud skipping in fixture

* Old build flow version

* Bump year

* Set OSearch sysctl in the test

---------

Co-authored-by: Carl Csaposs <carl.csaposs@canonical.com>

diff --git a/charmcraft.yaml b/charmcraft.yaml
--- a/charmcraft.yaml
+++ b/charmcraft.yaml
@@ -3,9 +3,20 @@
 
 type: charm
 bases:
-  - build-on:
-      - name: "ubuntu"
-        channel: "22.04"
-    run-on:
-      - name: "ubuntu"
-        channel: "22.04"
+  - name: ubuntu
+    channel: "22.04"
+    architectures: [amd64]
+  - name: ubuntu
+    channel: "22.04"
+    architectures: [arm64]
+
+parts:
+  charm:
+    override-pull: |
+      craftctl default
+      if [[ ! -f requirements.txt ]]
+      then
+          echo 'ERROR: Use "tox run -e build-dev" instead of calling "charmcraft pack" directly' >&2
+          exit 1
+      fi
+    charm-strict-dependencies: true
